from .userSerializer import User
from .medicoSerializer import Medico
from .enfermeroSerializer import Enfermero
from .auxiliarSerializer import Auxiliar
from .familiarSerializer import Familiar
from .sugerenciaSerializer import Sugerencia
from .pacienteSerializer import Paciente
from .historiaSerializer import Historiaclinica
from .signosvitalesSerializer import Signosvitales
from .detallesignosSerializer import Detallesignos