# Generated by Django 4.1.1 on 2022-09-18 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('idauxiliar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('idenfermero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('idfamiliar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('parentesto', models.CharField(max_length=30, verbose_name='Parentesco')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Signosvitales',
            fields=[
                ('idsignosvitales', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('idsugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('entorno', models.CharField(max_length=20, verbose_name='Entorno')),
                ('fecha', models.DateField()),
                ('sugerencia', models.CharField(max_length=500, verbose_name='Sugerencia')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellido')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha')),
                ('latitud', models.CharField(max_length=30, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=30, verbose_name='Longitud')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('idauxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='authApp.auxiliar')),
                ('idenfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='authApp.enfermero')),
                ('idfamiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='authApp.familiar')),
                ('idmedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='authApp.medico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('idhistoria', models.AutoField(primary_key=True, serialize=False)),
                ('encasa', models.BooleanField(default=1)),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historiaclinica', to='authApp.paciente')),
                ('idsugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historiaclinica', to='authApp.sugerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Detallesignos',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=500, verbose_name='Detalle')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detallesignos', to='authApp.paciente')),
                ('idsignosvitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detallesignos', to='authApp.signosvitales')),
            ],
        ),
    ]
