# Generated by Django 4.1.1 on 2022-09-25 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auxiliar_enfermero_familiar_signosvitales_sugerencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cuidad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fechanacimento',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='logitud',
            new_name='longitud',
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallesignos',
            name='idpaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallesignos', to='authApp.paciente'),
        ),
        migrations.AlterField(
            model_name='detallesignos',
            name='idsignosvitales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallesignos', to='authApp.signosvitales'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='apellidos',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='enfermero',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='idpaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='authApp.paciente'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='idsugerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='authApp.sugerencia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idauxiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.auxiliar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idenfermero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.enfermero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idfamilar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idmedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.medico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
