from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .enfermeroViewCrud import enfermero_api_view
from .enfermeroViewCrud import enfermero_detail_view
from .familiarView import familiar_api_view
from .familiarView import familiar_detail_view
from .auxiliarView import auxiliar_api_view
from .auxiliarView import auxiliar_detail_view
from .medicoView import medico_api_view
from .medicoView import medico_detail_view
from .pacienteView import paciente_api_view
from .pacienteView import paciente_detail_view